/** Build settings
  */
ThisBuild / scalaVersion := "3.3.7"

ThisBuild / tpolecatDefaultOptionsMode := org.typelevel.sbt.tpolecat.DevMode

/** GitHub Actions CI/CD workflow settings
  *
  * The workflows are automatically generated by the sbt-github-actions plugin.
  * The build configuration below is used to customize the generated workflow
  * steps.
  */

ThisBuild / githubWorkflowJavaVersions := Seq(JavaSpec.temurin("11"))

ThisBuild / githubWorkflowPublishTargetBranches := Seq()

ThisBuild / githubWorkflowBuild := Seq(
  WorkflowStep.Sbt(
    List("scalafmtSbtCheck", "scalafmtCheckAll"),
    name = Some("Check formatting")
  ),
  WorkflowStep.Sbt(
    List("tpolecatCiMode", "compile"),
    name = Some("Compile")
  ),
  WorkflowStep.Sbt(
    List("tpolecatCiMode", "test"),
    name = Some("Run tests")
  )
)

/** Custom `ci` task that runs all sbt commands defined in the GitHub Actions
  * workflow build steps. This keeps local CI execution in sync with the
  * generated workflow file.
  */
lazy val ci = taskKey[Unit]("Run all GitHub Actions build steps locally")

ci := {
  val log = streams.value.log
  val commands = (ThisBuild / githubWorkflowBuild).value.flatMap {
    case sbtStep: WorkflowStep.Sbt => sbtStep.commands
    case _                         => Nil
  }
  log.info(s"Running CI commands: ${commands.mkString(", ")}")
  val _ = commands.foldLeft(state.value) { (s, cmd) =>
    sbt.MainLoop.processCommand(sbt.Exec(cmd, None), s)
  }
}

/** Dependencies and versions
  */

lazy val mainDependencies: Seq[ModuleID] = Seq()

lazy val testDependencies: Seq[ModuleID] = Seq(
  "org.scalameta" %% "munit" % "1.3.2",
  "org.scalameta" %% "munit-scalacheck" % "1.3.0"
).map(_ % Test)

/** Project settings
  *
  * Here dependencies, settings, and tasks are wired up for the sbt projects.
  */

lazy val rootProject = (project in file("."))
  .settings(
    Seq(
      name := "cronh",
      version := "0.0.0",
      organization := "io.github.algebrazebra",
      libraryDependencies ++= mainDependencies ++ testDependencies
    )
  )
